create table Person (
    ID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO Person(ID, NAME) VALUES(1001,'Brittany');
INSERT INTO Person(ID, NAME) VALUES(1002,'Varun');
INSERT INTO Person(ID, NAME) VALUES(1003,'Ash');
INSERT INTO Person(ID, NAME) VALUES(1004,'John');
INSERT INTO Person(ID, NAME) VALUES(1005,'Brad');
INSERT INTO Person(ID, NAME) VALUES(1006,'Vasu');